name: Test
on: [push]
jobs:
  test_in_docker:
    runs-on: ubuntu-latest
    name: Run all tests in docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: docker build -f test/Dockerfile -t polygraph_test .
      - name: Run
        run: docker run -t polygraph_test
