name: Test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run all tests in docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t polygraph_test .
      - name: Run
        run: docker run --privileged -t polygraph_test
